# fly.toml app configuration file generated for gsl-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gsl-backend-api"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"

[env]
  PORT = "8080"
  GIN_MODE = "release"
  DB_SSLMODE = "require"
