// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"gsl-backend/models"
)


type AuthResponse struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Username  string  `json:"username"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	FirstName *string `json:"first_name,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
}

// Blog GraphQL input types
type BlogInput struct {
	Title        string  `json:"title"`
	Content      string  `json:"content"`
	Excerpt      *string `json:"excerpt,omitempty"`
	FeaturedImage *string `json:"featured_image,omitempty"`
	Status       *string `json:"status,omitempty"`
	Tags         *string `json:"tags,omitempty"`
}

type UpdateBlogInput struct {
	Title        *string `json:"title,omitempty"`
	Content      *string `json:"content,omitempty"`
	Excerpt      *string `json:"excerpt,omitempty"`
	FeaturedImage *string `json:"featured_image,omitempty"`
	Status       *string `json:"status,omitempty"`
	Tags         *string `json:"tags,omitempty"`
}

// News GraphQL input types (stubs for future implementation)
type NewsInput struct {
	Title        string   `json:"title"`
	Content      string   `json:"content"`
	Excerpt      *string  `json:"excerpt,omitempty"`
	FeaturedImage *string `json:"featured_image,omitempty"`
	Status       *string  `json:"status,omitempty"`
	Category     *string  `json:"category,omitempty"`
}

type UpdateNewsInput struct {
	Title        *string  `json:"title,omitempty"`
	Content      *string  `json:"content,omitempty"`
	Excerpt      *string  `json:"excerpt,omitempty"`
	FeaturedImage *string `json:"featured_image,omitempty"`
	Status       *string  `json:"status,omitempty"`
	Category     *string  `json:"category,omitempty"`
}
