package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"
	"strings"
	"gsl-backend/database"
	"gsl-backend/graph/generated"
	"gsl-backend/graph/model"
	"gsl-backend/models"
	"gsl-backend/utils"

	"gorm.io/gorm"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	// Check if user already exists (normalize email to lowercase)
	var existingUser models.User
	if err := database.DB.Where("email = ? OR username = ?", strings.ToLower(input.Email), input.Username).First(&existingUser).Error; err == nil {
		return nil, errors.New("user with this email or username already exists")
	}

	// Hash password
	hashedPassword, err := utils.HashPassword(input.Password)
	if err != nil {
		return nil, errors.New("failed to hash password")
	}

	// Prepare first name and last name
	var firstName, lastName string
	if input.FirstName != nil {
		firstName = *input.FirstName
	}
	if input.LastName != nil {
		lastName = *input.LastName
	}

	// Create user (normalize email to lowercase)
	user := models.User{
		Username:  input.Username,
		Email:     strings.ToLower(input.Email),
		Password:  hashedPassword,
		FirstName: firstName,
		LastName:  lastName,
		Role:      "user", // Default role
		IsVerified: false,
		IsPremium:  false,
	}

	if err := database.DB.Create(&user).Error; err != nil {
		return nil, errors.New("failed to create user")
	}

	// Generate token
	token, err := utils.GenerateToken(user.ID, user.Email, user.Role)
	if err != nil {
		return nil, errors.New("failed to generate token")
	}

	return &model.AuthResponse{
		Token: token,
		User:  &user,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	// Find user
	var user models.User
	if err := database.DB.Where("email = ?", strings.ToLower(input.Email)).First(&user).Error; err != nil {
		// Check if error is "record not found" - this is expected for invalid credentials
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errors.New("invalid credentials")
		}
		// For other database errors, return generic error
		return nil, errors.New("invalid credentials")
	}

	// Check password
	if !utils.CheckPasswordHash(input.Password, user.Password) {
		return nil, errors.New("invalid credentials")
	}

	// Generate token
	token, err := utils.GenerateToken(user.ID, user.Email, user.Role)
	if err != nil {
		return nil, errors.New("failed to generate token")
	}

	return &model.AuthResponse{
		Token: token,
		User:  &user,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// In a stateless JWT system, logout is typically handled client-side
	// You can implement token blacklisting here if needed
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	userID, exists := ctx.Value("user_id").(string)
	if !exists || userID == "" {
		return nil, errors.New("unauthorized: user not authenticated")
	}

	var user models.User
	if err := database.DB.Where("id = ?", userID).First(&user).Error; err != nil {
		return nil, errors.New("user not found")
	}

	return &user, nil
}

// Stub implementations for Blog GraphQL methods (not used, but required for compilation)
func (r *mutationResolver) CreateBlog(ctx context.Context, input model.BlogInput) (*models.Blog, error) {
	return nil, errors.New("use REST API /api/admin/blogs instead")
}

func (r *mutationResolver) UpdateBlog(ctx context.Context, id string, input model.UpdateBlogInput) (*models.Blog, error) {
	return nil, errors.New("use REST API /api/admin/blogs/:id instead")
}

func (r *mutationResolver) DeleteBlog(ctx context.Context, id string) (bool, error) {
	return false, errors.New("use REST API /api/admin/blogs/:id instead")
}

func (r *mutationResolver) PublishBlog(ctx context.Context, id string) (*models.Blog, error) {
	return nil, errors.New("use REST API /api/admin/blogs/:id instead")
}

func (r *queryResolver) Blogs(ctx context.Context, limit *int, offset *int, published *bool) ([]*models.Blog, error) {
	return nil, errors.New("use REST API /api/blogs instead")
}

func (r *queryResolver) Blog(ctx context.Context, id *string, slug *string) (*models.Blog, error) {
	return nil, errors.New("use REST API /api/blogs/slug/:slug instead")
}

// Stub implementations for News (not implemented yet)
func (r *mutationResolver) CreateNews(ctx context.Context, input model.NewsInput) (*models.News, error) {
	return nil, errors.New("news not implemented")
}

func (r *mutationResolver) UpdateNews(ctx context.Context, id string, input model.UpdateNewsInput) (*models.News, error) {
	return nil, errors.New("news not implemented")
}

func (r *mutationResolver) DeleteNews(ctx context.Context, id string) (bool, error) {
	return false, errors.New("news not implemented")
}

func (r *mutationResolver) PublishNews(ctx context.Context, id string) (*models.News, error) {
	return nil, errors.New("news not implemented")
}

func (r *queryResolver) News(ctx context.Context, limit *int, offset *int, published *bool, category *string) ([]*models.News, error) {
	return nil, errors.New("news not implemented")
}

func (r *queryResolver) NewsItem(ctx context.Context, id *string, slug *string) (*models.News, error) {
	return nil, errors.New("news not implemented")
}

func (r *mutationResolver) UpdateSettings(ctx context.Context, key string, value string) (*models.Settings, error) {
	return nil, errors.New("settings not implemented in GraphQL")
}

func (r *mutationResolver) ToggleUserPosting(ctx context.Context, enabled bool) (*models.Settings, error) {
	return nil, errors.New("use REST API /api/admin/blogs/settings instead")
}

func (r *queryResolver) Settings(ctx context.Context, key *string) (*models.Settings, error) {
	return nil, errors.New("settings not implemented in GraphQL")
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
